spring:
  application:
    name: tc4-srv-gateway-pagamento
  data:
    mongodb:
      host: mongo-container
      database: pagamento
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASS:rootpass}
      authentication-database: admin
server:
  port: 8084
